name: Codebase linter
on:
  push:
    branches:
      - master
jobs:
  lint:
    if: ${{ github.actor != 'Mabibot' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MABIBOT_GITHUB_ACTION_EXPO_MANAGED_TEMPLATE }}
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
      - run: git config user.name Mabibot
      - run: git config user.email devops@appandflow.com
      - run: git add .
        continue-on-error: true
      - run: git commit -m "Lint codebase"
        continue-on-error: true
      - run: git push
